# Default values for gomessage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: gomessage

deployment:
  replicas: 2

service:
  port: 80
  targetPort: 7077
  nodePort: 32077

pvc:
  storage: 1Gi
